// JsFromRoutes CacheKey ad52b8e3e4955c8eb09bd7158f1ced9c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  all: /* #__PURE__ */ definePathHelper('get', '/categories/api'),
  index: /* #__PURE__ */ definePathHelper('get', '/categories'),
  create: /* #__PURE__ */ definePathHelper('post', '/categories'),
  new: /* #__PURE__ */ definePathHelper('get', '/categories/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/categories/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/categories/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/categories/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/categories/:id'),
}
