// JsFromRoutes CacheKey 67d3fe0d714d94aa8ea10e20e6db8de8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/expenses'),
  create: /* #__PURE__ */ definePathHelper('post', '/expenses'),
  new: /* #__PURE__ */ definePathHelper('get', '/expenses/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/expenses/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/expenses/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/expenses/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/expenses/:id'),
}
