// JsFromRoutes CacheKey 7d8ab1c632abdc99093f0934c5444657
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  all: /* #__PURE__ */ definePathHelper('get', '/expenses/api'),
  index: /* #__PURE__ */ definePathHelper('get', '/expenses'),
  create: /* #__PURE__ */ definePathHelper('post', '/expenses'),
  new: /* #__PURE__ */ definePathHelper('get', '/expenses/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/expenses/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/expenses/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/expenses/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/expenses/:id'),
}
